[build]
  command = "mkdir -p .publish && rsync -a --exclude '.git' --exclude '.publish' --exclude '.netlify' --exclude 'images' --exclude 'moodle' --exclude '.DS_Store' ./ .publish/"
  publish = ".publish"
